/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CountryQueryOpionsImport } from './routes/countryQueryOpions'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as CountryCountryCodeImport } from './routes/country/$countryCode'

// Create/Update Routes

const CountryQueryOpionsRoute = CountryQueryOpionsImport.update({
  id: '/countryQueryOpions',
  path: '/countryQueryOpions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const CountryCountryCodeRoute = CountryCountryCodeImport.update({
  id: '/country/$countryCode',
  path: '/country/$countryCode',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/countryQueryOpions': {
      id: '/countryQueryOpions'
      path: '/countryQueryOpions'
      fullPath: '/countryQueryOpions'
      preLoaderRoute: typeof CountryQueryOpionsImport
      parentRoute: typeof rootRoute
    }
    '/country/$countryCode': {
      id: '/country/$countryCode'
      path: '/country/$countryCode'
      fullPath: '/country/$countryCode'
      preLoaderRoute: typeof CountryCountryCodeImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countryQueryOpions': typeof CountryQueryOpionsRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countryQueryOpions': typeof CountryQueryOpionsRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/countryQueryOpions': typeof CountryQueryOpionsRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countryQueryOpions'
    | '/country/$countryCode'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countryQueryOpions'
    | '/country/$countryCode'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/countryQueryOpions'
    | '/country/$countryCode'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryQueryOpionsRoute: typeof CountryQueryOpionsRoute
  CountryCountryCodeRoute: typeof CountryCountryCodeRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryQueryOpionsRoute: CountryQueryOpionsRoute,
  CountryCountryCodeRoute: CountryCountryCodeRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/countryQueryOpions",
        "/country/$countryCode",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/countryQueryOpions": {
      "filePath": "countryQueryOpions.tsx"
    },
    "/country/$countryCode": {
      "filePath": "country/$countryCode.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
