/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CountryIndexImport } from './routes/country/index'
import { Route as CountryCountryCodeImport } from './routes/country/$countryCode'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CountryIndexRoute = CountryIndexImport.update({
  id: '/country/',
  path: '/country/',
  getParentRoute: () => rootRoute,
} as any)

const CountryCountryCodeRoute = CountryCountryCodeImport.update({
  id: '/country/$countryCode',
  path: '/country/$countryCode',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/country/$countryCode': {
      id: '/country/$countryCode'
      path: '/country/$countryCode'
      fullPath: '/country/$countryCode'
      preLoaderRoute: typeof CountryCountryCodeImport
      parentRoute: typeof rootRoute
    }
    '/country/': {
      id: '/country/'
      path: '/country'
      fullPath: '/country'
      preLoaderRoute: typeof CountryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/country': typeof CountryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/country': typeof CountryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/country/$countryCode': typeof CountryCountryCodeRoute
  '/country/': typeof CountryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/country/$countryCode' | '/country'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/country/$countryCode' | '/country'
  id: '__root__' | '/' | '/country/$countryCode' | '/country/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCountryCodeRoute: typeof CountryCountryCodeRoute
  CountryIndexRoute: typeof CountryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCountryCodeRoute: CountryCountryCodeRoute,
  CountryIndexRoute: CountryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/country/$countryCode",
        "/country/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/country/$countryCode": {
      "filePath": "country/$countryCode.tsx"
    },
    "/country/": {
      "filePath": "country/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
